name: google_sign_in_helper
description: Make it easier for you to use google sign in on all platforms.
version: 0.0.2
homepage: https://github.com/lamnhan066/google_sign_in_helper
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.1
  google_sign_in: ^6.2.1
  google_sign_in_dartio: ^0.3.0
  http: ^1.2.2
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
